@kmsHost = http://localhost:8083
@workerId = 1775612047560224
@teamLeaderId = 1775611674533123
@departmentLeaderId = 1775611849849457
@adminId = 1774850514911459
@hrmId = 1775611890201688
@articleId = 1775021444000913

### 팀장 승인
POST {{kmsHost}}/api/kms/tl/articles/{{articleId}}/approval
Content-Type: application/json
Authorization: Bearer {{accessToken}}
X-Employee-Id: {{teamLeaderId}}

{
  "status": "APPROVE",
  "reviewComment": "내용 검토를 마쳤고 1차 승인 기준을 충족합니다."
}

### 팀장 반려
POST {{kmsHost}}/api/kms/tl/articles/{{articleId}}/approval
Content-Type: application/json
Authorization: Bearer {{accessToken}}
X-Employee-Id: {{teamLeaderId}}

{
  "status": "REJECT",
  "reviewComment": "원인 분석과 재발 방지 방안이 부족합니다. 보완 후 다시 제출해주세요."
}

### 팀장 보류
POST {{kmsHost}}/api/kms/tl/articles/{{articleId}}/approval
Content-Type: application/json
Authorization: Bearer {{accessToken}}
X-Employee-Id: {{teamLeaderId}}

{
  "status": "PENDING",
  "reviewComment": "추가 확인이 필요하므로 현재 단계에서는 보류 처리합니다."
}
