@kmsHost = http://localhost:8083
@workerId = 1775612047560224
@teamLeaderId = 1775611674533123
@departmentLeaderId = 1775611849849457
@adminId = 1774850514911459
@hrmId = 1775611890201688
@tagId = 1775544386810690

### 전체 태그 목록 조회
GET {{kmsHost}}/api/kms/tags
Authorization: Bearer {{accessToken}}

### 태그 등록
POST {{kmsHost}}/api/kms/admin/articles/tags
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "tagName": "HTTP테스트태그"
}

> {%
    client.global.set("tagId", response.body.data);
%}

### 태그 수정
PUT {{kmsHost}}/api/kms/admin/articles/tags
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "tagId": {{tagId}},
  "tagName": "HTTP테스트태그수정"
}

### 태그 삭제
DELETE {{kmsHost}}/api/kms/admin/articles/tags
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "tagId": {{tagId}}
}
